# setup
load libraries define some functions
```{r}
# Set the working directory to the specified path
setwd("C:/Users/cclab/Documents/GitHub/Dev2019/GAM")

# Load necessary libraries/packages
library(dplyr)      # Data manipulation 
library(ggplot2)    # Data visualization
library(gratia)     # Tools for GAM models
library(gridExtra)  # Arranging ggplot2 plots on a grid
library(lubridate)  # Work with date-times
library(mgcv)       # GAM and GAMM functions
library(purrr)      # Functional programming tools
library(stringr)    # String manipulation
library(tidyr)      # Data tidying
library(xtable)     # Export tables to various formats
```

```{r}
# Define a function to plot raw data, fitted values, and pointwise 95% confidence intervals from a GAMM
plot_gamm <- function(model,predictor = 'age', x_axis_label = '', y_axis_label = '', sig = TRUE, color_map = NULL) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]]
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  plotdat <- data.frame(cbind(dat_clean[[predictor]], pred$fit, pred$se))
  plotdat <- plotdat %>% 
    mutate(outcome = 1) 
  names(plotdat) <- c(predictor, 'fit', 'se', outcome)
  
      # If a color map is provided, use it. Otherwise, use the default color.
 if (!is.null(color_map)) {
    individual_colors <- dat$ID %>% as.character() %>% factor() %>% levels() %>% setNames(., .) %>% color_map[.]
} else {
    individual_colors <- "blue"  # or any other default color you'd like
}
  if (sig == TRUE){
    plotcolor_fit <- '#646464'
  } else {
    plotcolor_fit <- '#646464'
  }
  gammplot <- ggplot(dat, aes_string(x = predictor, y = outcome, group = "ID", color = "ID")) + 
    geom_line(alpha = .8) + 
    geom_point(alpha = .3, shape = 16) +
    (if (!is.null(color_map)) scale_color_manual(values = color_map) else scale_color_identity()) +
    geom_ribbon(data = plotdat, aes_string(x = predictor, ymin = "fit - (1.96 * se)", ymax = "fit + (1.96 * se)"), alpha = .5, fill = plotcolor_fit, inherit.aes = FALSE) + 
    geom_line(data = plotdat, aes_string(x = predictor, y = "fit"), color = plotcolor_fit, inherit.aes = FALSE) + 
    
    labs(x = x_axis_label, 
         y = y_axis_label) +
    theme_bw() +
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = 'black')) +
    theme(axis.title = element_text(size = 11),
          axis.text = element_text(size = 10))
  return(gammplot)
}

# Define a function for post-hoc analysis to identify periods of developmental change
calc_dev_change <- function(model) {
  # Calculate derivatives of the model
  deriv <- gratia::derivatives(model)
  deriv <- deriv %>%
    mutate(sig = !(0 > lower & 0 < upper)) 
  # Identify range of significant change
  ranges <- list(c(min(deriv$data[deriv$sig == TRUE]), 
                 max(deriv$data[deriv$sig == TRUE])))
  return(ranges[[1]])
}

get_peak_and_velocity <- function(model, predictor = 'age') {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]]
  # Clean the data
  dat_clean <- dat %>% drop_na(all_of(outcome))
  
  # Create new data for prediction
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  
  # Predict the values
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Create a dataframe with predictions
  pred_dat <- data.frame(predictor = dat_clean[[predictor]], fit = pred$fit)
  
  # Find the peak value's predictor (e.g., age at which outcome is maximized)
  peak_x <- pred_dat$predictor[which.max(pred_dat$fit)]
  peak_y <- max(pred_dat$fit)
  
  # Determine the Peak Rate of Change (Velocity)
  derivi <- gratia::derivatives(model$gam)
  peak_velocity_x <- derivi$data[which.max(abs(derivi$derivative))]
  closest_idx <- which.min(abs(pred_dat$predictor - peak_velocity_x))
  peak_velocity_y <- pred_dat$fit[closest_idx]
  
  return(list(peak_value_x = peak_x, peak_velocity_x = peak_velocity_x, peak_value_y = peak_y, peak_velocity_y = peak_velocity_y))
}

my_color <- c("OLI" = "#E73133", "PIC" = "#4B8BBF", "QUA" = "#5FB75C", "ROS" = "#FF8C1A",
              "SON" = "#DDCF6E", "TRI" = "#AF673E", "UNI" = "#F88EC5", "VIK" = "#A3A3A3")
```

# read data
```{r}
# Read the dataset from a CSV file
dat <- read.csv('FA_contra_and_bi.csv', 
                stringsAsFactors = FALSE) 
```
# clean data
```{r}
header_list <- as.list(names(dat))
names_to_omit <- c("age","mature","ID","hemi")
header_list <- header_list[-match(names_to_omit, header_list)]

list_all =  header_list
print(list_all)
```

# model on age
```{r}
list_of_regressor = c('age')
list_of_regressor_string = c('age')

# Initialize a list to store the models
models_age_list <- list()
peak_and_velocity_age_list <- list()
for(L in 1:length(list_of_regressor)){
  regressor = list_of_regressor[L]
  regressor_string = list_of_regressor_string[L]
  
  for(R in 1:length(list_all)){
    current_regions = list_all[[R]]
    for(region in current_regions){
      print(paste("Regressor:", regressor, "| Region:", region))
      
      # Define a formula for the GAMM to model the current 'region' as a smoothed function of the current 'regressor'
      model_formula <- as.formula(paste(region, "~ s(", regressor, ", k = 10, fx = FALSE, bs = 'cr')"))
      
      # Fit the GAMM with the formula, and a random effect of 'id' on the current 'regressor'
      gamm_vol_on_dev <- gamm(as.formula(model_formula), 
                               random = list(ID=~age),
                               data = dat %>% drop_na(all_of(c(region, regressor))),
                               method = 'REML')
      peak_and_velocity <- get_peak_and_velocity(model = gamm_vol_on_dev, predictor = regressor)
      # Save the model to the list
      model_name <- paste(region, regressor, sep="_")
      models_age_list[[model_name]] <- gamm_vol_on_dev
      peak_and_velocity_age_list[[model_name]] <- peak_and_velocity
    }
  }
}
```

# model on mature
```{r}
list_of_regressor = c('mature')
list_of_regressor_string = c('mature')

# Initialize a list to store the models
models_mat_list <- list()
peak_and_velocity_mat_list <- list()

for(L in 1:length(list_of_regressor)){
  regressor = list_of_regressor[L]
  regressor_string = list_of_regressor_string[L]
  
  for(R in 1:length(list_all)){
    current_regions = list_all[[R]]
    for(region in current_regions){
      print(paste("Regressor:", regressor, "| Region:", region))
      
      # Define a formula for the GAMM to model the current 'region' as a smoothed function of the current 'regressor'
      model_formula <- as.formula(paste(region, "~ s(", regressor, ", k = 10, fx = FALSE, bs = 'tp')"))
      
      # Fit the GAMM with the formula, and a random effect of 'id' on the current 'regressor'
      gamm_vol_on_dev <- gamm(as.formula(model_formula), 
                               random = list(ID=~1+mature),
                               data = dat %>% drop_na(all_of(c(region, regressor))),
                               method = 'REML')
      peak_and_velocity <- get_peak_and_velocity(model = gamm_vol_on_dev, predictor = regressor)
      # Save the model to the list
      model_name <- paste(region, regressor, sep="_")
      models_mat_list[[model_name]] <- gamm_vol_on_dev
      peak_and_velocity_mat_list[[model_name]] <- peak_and_velocity
    }
  }
}
```

# plot on age
```{r}
# Loop through the model names in models_list
for(model_name in names(models_age_list)) {
  
  # Extract the current model
  current_model <- models_age_list[[model_name]]
  current_peak <- peak_and_velocity_age_list[[model_name]]
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 57.9
  } else {
    sig <- TRUE
  }
  
  # Plot this model
  current_plot <- plot_gamm(
    predictor = 'age',
    model = current_model, 
    y_axis_lab = 'Outcome Value',
    sig = sig, color_map = my_color)
  # Annotate the plot with a bar indicating significant developmental change
  # Extract y-axis range from current_plot
  y_range <- layer_scales(current_plot)$y$range$range
  
  # Set ymin and ymax based on y_range
  ymin_value <- y_range[1] - 0.01 * (y_range[2] - y_range[1])
  ymax_value <- y_range[1] 
  
  current_plot <- current_plot + labs(title = model_name) +
    annotate(geom = "rect", 
             xmin = dev_change[1], 
             xmax = dev_change[2], 
             ymin = ymin_value, 
             ymax = ymax_value, 
             fill = '#476FD1') +
    geom_point(aes(x = current_peak$peak_value_x, y = current_peak$peak_value_y), shape = 24, size = 3, color = "red") +
    geom_point(aes(x = current_peak$peak_velocity_x, y = current_peak$peak_velocity_y, type = "response"), shape = 1, size = 3, color = "blue")+
    geom_vline(xintercept = 57.9, linetype="dashed", color = "brown")
  print(current_plot)
  
  # Define file names based on the model name
  png_file_name <- paste0(model_name, '.png')
  pdf_file_name <- paste0(model_name, '.pdf')
  
  # Save the plot in PNG format
  # ggsave(png_file_name, plot = current_plot, device = 'png', width = 8, height = 4, dpi = 300)

  # Save the plot in PDF format
  # ggsave(pdf_file_name, plot = current_plot, device = 'pdf', width = 8, height = 4)
}
```

# plot on mature
```{r}
# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", model_name, "| Significant Developmental Change:", toString(dev_change)))
    if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }
  # Plot this model
  current_plot <- plot_gamm(
    predictor = 'mature',
    model = current_model, 
    y_axis_lab = 'Outcome Value',
    sig = sig, color_map = my_color)
  # Annotate the plot with a bar indicating significant developmental change
  # Extract y-axis range from current_plot
  y_range <- layer_scales(current_plot)$y$range$range
    # Set ymin and ymax based on y_range
  ymin_value <- y_range[1] - 0.01 * (y_range[2] - y_range[1])
  ymax_value <- y_range[1] 
  
  current_plot <- current_plot + labs(title = model_name) +
    annotate(geom = "rect", 
             xmin = dev_change[1], 
             xmax = dev_change[2], 
             ymin = ymin_value, 
             ymax = ymax_value, 
             fill = '#646464') +
    geom_point(aes(x = current_peak$peak_value_x, y = current_peak$peak_value_y), shape = 24, size = 3, color = "red") +
    geom_point(aes(x = current_peak$peak_velocity_x, y = current_peak$peak_velocity_y, type = "response"), shape = 1, size = 3, color = "blue") +
    geom_vline(xintercept = 0, linetype="dashed", color = "brown") +
    scale_x_continuous(labels = function(x) x)
  print(current_plot)
  # Define file names based on the model name
  png_file_name <- paste0(model_name, '.png')
  pdf_file_name <- paste0(model_name, '.pdf')
  
  # Save the plot in PNG format
  # ggsave(png_file_name, plot = current_plot, device = 'png', width = 3, height = 3, dpi = 300)

  # Save the plot in PDF format
  ggsave(pdf_file_name, plot = current_plot, device = 'pdf', width = 3, height = 3)


}
```



# find dev change
```{r}
# # Initialize an empty data frame to store dev_change information
# dev_change_df <- data.frame(region = character(), 
#                             mature_value = numeric(),
#                             derivative = numeric(),
#                             stringsAsFactors = FALSE)
# 
# for(model_name in names(models_mat_list)) {
#   # Extract the current model
#   current_model <- models_mat_list[[model_name]]
#   
#   # Extract the region name from the model name
#   region_name <- strsplit(model_name, "_")[[1]][2]
#   
#   # Identify significant periods of developmental change using the calc_dev_change function
#   dev_change <- calc_dev_change(current_model)
#   
#   if (!all(is.infinite(dev_change))) {
#     # Create a sequence of points within the significant change period
#     mature_values <- seq(from = dev_change[1], to = dev_change[2], by = 1)
#     
#     # Calculate the derivative at each point
#     derivatives <- sapply(mature_values, function(x) {
#       gratia::derivatives(current_model$gam, data = data.frame(mature = x))$derivative
#     })
#     
#     # Add the dev_change information to the data frame
#     dev_change_df <- rbind(dev_change_df, data.frame(region = rep(region_name, length(mature_values)), 
#                                                      mature_value = mature_values,
#                                                      derivative = derivatives,
#                                                      stringsAsFactors = FALSE))
#   }
# }
```

```{r}
# Initialize an empty data frame to store dev_change information
dev_change_df <- data.frame(region = character(),
                            mature_value = numeric(),
                            region_value = numeric(),
                            percent_change = numeric(),
                            stringsAsFactors = FALSE)

# Initialize an empty data frame to store regions with infinite dev_change
inf_dev_change_df <- data.frame(region = character(),
                                mature_value = numeric(),
                                region_value = numeric(),
                                percent_change = numeric(),
                                stringsAsFactors = FALSE)

for (model_name in names(models_mat_list)) {
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  
  # Extract the region name from the model name
  model_name_parts <- strsplit(model_name, "_")[[1]]
  region_name <- paste(model_name_parts[2:(length(model_name_parts)-1)], collapse = "_")
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  
  if (all(is.infinite(dev_change))) {
    # Add the region with infinite dev_change to inf_dev_change_df
    inf_dev_change_df <- rbind(inf_dev_change_df, data.frame(region = region_name,
                                                            mature_value = NA,
                                                            region_value = 0,
                                                            percent_change = 0,
                                                            stringsAsFactors = FALSE))
  } else {
    # Create a sequence of points within the significant change period using 1/10 of the mature value as the step length
    mature_values <- seq(from = dev_change[1], to = dev_change[2], by = 1)
    
    # Predict the region values at each point
    region_values <- predict(current_model$gam, newdata = data.frame(mature = mature_values))
    
    # Calculate the percentage change in the region values
    percent_changes <- c(NA, diff(region_values) / region_values[-length(region_values)] * 100)
    
    # Add the dev_change information to the data frame
    dev_change_df <- rbind(dev_change_df, data.frame(region = rep(region_name, length(mature_values)),
                                                     mature_value = mature_values,
                                                     region_value = region_values,
                                                     percent_change = percent_changes,
                                                     stringsAsFactors = FALSE))
  }
}

# Combine dev_change_df and inf_dev_change_df
combined_df <- rbind(dev_change_df, inf_dev_change_df)
```


```{r}
# Calculate the start and end positions for each rectangle
combined_df <- combined_df %>%
  group_by(region) %>%
  mutate(start = lag(mature_value, default = first(mature_value)),
         end = lead(mature_value, default = last(mature_value))) %>%
  ungroup()

# Calculate the length of dev_change for each region
region_dev_change_length <- combined_df %>%
  group_by(region) %>%
  summarize(dev_change_length = max(mature_value))

# Sort the regions based on dev_change_length
sorted_regions <- region_dev_change_length$region[order(region_dev_change_length$dev_change_length)]

# Create the plot using geom_rect
current_plot <- ggplot(combined_df, aes(xmin = start,
                          xmax = end,
                          ymin = as.numeric(factor(region, levels = sorted_regions)) - 0.4,
                        ymax = as.numeric(factor(region, levels = sorted_regions)) + 0.4,
                        fill = percent_change)) +
  geom_rect() +
  scale_fill_gradient2(low = "darkblue", mid = "white", high = "red", midpoint = 0,
                       name = "% change per month",
                       limits = range(combined_df$percent_change, na.rm = TRUE)) +
  labs(x = "Maturation age", y = "Tracts", title = "FA") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 10, hjust = 1),
        axis.text.x = element_text(size = 10, angle = 0, hjust = 1),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(breaks = seq_along(sorted_regions), labels = sorted_regions)

print(current_plot)
```
```{r}
# Adding a new column to identify tracks ending with "_contra"
combined_df <- combined_df %>%
  mutate(track_type = ifelse(grepl("_contra$", region), "With _contra", "Without _contra"))

# Define a function to generate the plot based on track type
generate_plot <- function(data, title_suffix) {
  # Calculate the start and end positions for each rectangle
  data <- data %>%
    group_by(region) %>%
    mutate(start = lag(mature_value, default = first(mature_value)),
           end = lead(mature_value, default = last(mature_value))) %>%
    ungroup()

  # Calculate the length of dev_change for each region
  region_dev_change_length <- data %>%
    group_by(region) %>%
    summarize(dev_change_length = max(mature_value))

  # Sort the regions based on dev_change_length
  sorted_regions <- region_dev_change_length$region[order(region_dev_change_length$dev_change_length)]

  # Create and return the plot using geom_rect
  ggplot(data, aes(xmin = start, xmax = end,
                   ymin = as.numeric(factor(region, levels = sorted_regions)) - 0.4,
                   ymax = as.numeric(factor(region, levels = sorted_regions)) + 0.4,
                   fill = percent_change)) +
    geom_rect() +
    scale_fill_gradient2(low = "darkblue", mid = "white", high = "red", midpoint = 0,
                         name = "% change per month",
                         limits = range(c(-1.5, 2.0), na.rm = TRUE)) +
    labs(x = "Maturation age", y = "Tracts", title = paste("FA", title_suffix)) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 10, hjust = 1),
          axis.text.x = element_text(size = 10, angle = 0, hjust = 1),
          plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(colour = "black")) +
    scale_y_continuous(breaks = seq_along(sorted_regions), labels = sorted_regions)
}

# Plot for tracks without "_contra"
data_without_contra <- combined_df %>%
  filter(track_type == "Without _contra")
plot_without_contra <- generate_plot(data_without_contra, "bilateral")
print(plot_without_contra)

# Plot for tracks with "_contra"
data_with_contra <- combined_df %>%
  filter(track_type == "With _contra")
plot_with_contra <- generate_plot(data_with_contra, "contralateral")
print(plot_with_contra)

```

save plot
```{r}
  # Define file names based on the model name
  png_file_name1 <- paste0('FA_timing.png')
  pdf_file_name1 <- paste0('FA_timing.pdf')
  
  # Save the plot in PNG format
  ggsave(png_file_name1, plot = plot_with_contra, device = 'png', width = 6, height = 6, dpi = 300)

  # Save the plot in PDF format
  ggsave(pdf_file_name1, plot = plot_with_contra, device = 'pdf', width = 6, height = 6)
```

# optional: stats
```{r}
# summary of significance of smooth terms for age for final models
# Extract model names from the list
model_names <- names(models_age_list)

# Extract significance information for each model
sumtab <- sapply(model_names, function (x) {
  model_gam <- models_age_list[[x]]$gam
  summary(model_gam)$s.table
})

AIC_r2 <- sapply(model_names, function (x) {
  model <- models_age_list[[x]]
  # Extract AIC
  aic_val <- summary(model$lme)$AIC
  # Extract R^2 (Percent deviance explained)
  r2_val <- summary(model$gam)$r.sq
  
  c(AIC = aic_val, R2 = r2_val)
  
})
AIC_r2_df <- as.data.frame(t(AIC_r2))

# Format the results
rownames(sumtab) <- c('edf', 'Ref.df', 'F', 'p-value')
sumtab <- as.data.frame(t(sumtab)) %>%
  tibble::rownames_to_column(., 'model') %>%
  select(-c('Ref.df'))
sumtab <- cbind(sumtab, p.adjust(sumtab$`p-value`, method = 'fdr'))
names(sumtab)[ncol(sumtab)] <- 'q-value'
sumtab <- sumtab %>% 
  mutate(survive_multcomp = ifelse(`q-value` < 0.05, 1, 0))
AIC_r2_df$model <- rownames(AIC_r2_df)
# Combine results
combined_df <- merge(sumtab, AIC_r2_df, by = "model")

# Save the results as a CSV
write.csv(combined_df, file = "vol_age_results.csv", row.names = FALSE)

```

```{r}
# summary of significance of smooth terms for mature for final models
# Extract model names from the list
model_names <- names(models_mat_list)

# Extract significance information for each model
sumtab <- sapply(model_names, function (x) {
  model_gam <- models_mat_list[[x]]$gam
  summary(model_gam)$s.table
})

AIC_r2 <- sapply(model_names, function (x) {
  model <- models_mat_list[[x]]
  # Extract AIC
  aic_val <- summary(model$lme)$AIC
  # Extract R^2 (Percent deviance explained)
  r2_val <- summary(model$gam)$r.sq
  
  c(AIC = aic_val, R2 = r2_val)
  
})
AIC_r2_df <- as.data.frame(t(AIC_r2))

# Format the results
rownames(sumtab) <- c('edf', 'Ref.df', 'F', 'p-value')
sumtab <- as.data.frame(t(sumtab)) %>%
  tibble::rownames_to_column(., 'model') %>%
  select(-c('Ref.df'))
sumtab <- cbind(sumtab, p.adjust(sumtab$`p-value`, method = 'fdr'))
names(sumtab)[ncol(sumtab)] <- 'q-value'
sumtab <- sumtab %>% 
  mutate(survive_multcomp = ifelse(`q-value` < 0.05, 1, 0))
AIC_r2_df$model <- rownames(AIC_r2_df)

# Combine results
combined_df <- merge(sumtab, AIC_r2_df, by = "model")

# Save the results as a CSV
write.csv(combined_df, file = "vol_mat_results.csv", row.names = FALSE)
```

# plot overlay curves raw
```{r}
plot_gamm_fitting_curves_raw <- function(model, predictor = 'age', sig = TRUE) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]] %>% str_trim()
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Calculate raw fitted values, standard errors, and confidence intervals
  plotdat <- data.frame(
    predictor = dat_clean[[predictor]],
    fit = pred$fit,
    se = pred$se.fit,
    lower = pred$fit - 1.96 * pred$se.fit,
    upper = pred$fit + 1.96 * pred$se.fit
  )
  plotdat <- plotdat %>% mutate(model_name = outcome)
  
  return(list(plotdat = plotdat))
}

```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  print(current_peak)
  
  # Clean the model name to avoid duplication
  clean_model_name <- sub("_mature$", "", model_name)
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", clean_model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }

  # Generate data for the current fitting curve
  raw_result <- plot_gamm_fitting_curves_raw(
    model = current_model,
    predictor = 'mature',
    sig = sig
  )
  current_plot_data <- raw_result$plotdat

  # Add the current plot data to the combined data frame
  current_plot_data$model_name <- clean_model_name
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
  
  # Only add max value and max velocity points if the curve is significant
  if (sig) {
    max_points <- data.frame(
      x = c(current_peak$peak_value_x, current_peak$peak_velocity_x),
      y = c(current_peak$peak_value_y, current_peak$peak_velocity_y),
      model_name = clean_model_name,
      point_type = c("max_value", "max_velocity")
    )
    
    max_points_data <- rbind(max_points_data, max_points)
  }
}

# Ensure the combined data has the correct column names
names(combined_plot_data)[1] <- "mature"

# Create the combined plot
combined_plot <- ggplot(combined_plot_data, aes(x = mature, y = fit, color = model_name)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0, linetype = "dashed", size = 0.5, show.legend = FALSE) + 
  geom_line(size = 1) +
  geom_point(data = max_points_data %>% filter(point_type == "max_value"),
             aes(x = x, y = y, color = model_name), shape = 24, size = 3, show.legend = FALSE) +
  geom_point(data = max_points_data %>% filter(point_type == "max_velocity"),
             aes(x = x, y = y, color = model_name), shape = 1, size = 3, show.legend = FALSE) +
  labs(x = 'Mid-adolescence age (mon.)', y = 'Volume') +
  theme_bw() +
  theme(
    panel.border = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.line = element_line(colour = 'black'),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    legend.position = c(0.85, 0.85), # Position legend inside the plot (x, y coordinates in [0, 1] range)
    legend.background = element_rect(fill = alpha('white', 0.5)), # Semi-transparent background for the legend
    legend.text = element_text(size = 8), # Reduce legend text size
    legend.key.size = unit(0.5, "lines")  # Reduce legend key size
  )

# # Save the combined plot
# ggsave('vol_seg_combined_plot_raw.png', plot = combined_plot, device = 'png', width = 6, height = 6, dpi = 300)
# ggsave('vol_seg_combined_plot_raw.pdf', plot = combined_plot, device = 'pdf', width = 6, height = 6)

# Print the combined plot
print(combined_plot)

```

# save fitted curve
```{r}
# Generate a sequence of maturation ages covering the range of beh data
maturation_ages <- seq(-30.90410959, 16.93150685, length.out = 100)

# Generate predicted values for RT over this range
predicted_FA <- predict(gamm_di_on_mat$gam, newdata = data.frame(mature = maturation_ages), type = "response")

# Create a data frame to save
data_to_save_DI <- data.frame(mature = maturation_ages, predicted_DI = predicted_DI)

# Save the data frame to a CSV file
write.csv(data_to_save_DI, "predicted_DI_vs_mature.csv", row.names = FALSE)

```


```{r}
generate_plotdat_for_predictor <- function(model, predictor = 'mature', seq_range = c(-30.90410959, 16.93150685), length_out = 100) {
  # Generate a sequence of maturation ages covering the range
  predictor_seq <- seq(seq_range[1], seq_range[2], length.out = length_out)
# Create a data frame with the predictor sequence
  newdat <- data.frame(predictor_seq)
  names(newdat) <- predictor
  
  # Generate predicted values over this range
  predicted_values <- predict.gam(model$gam, 
                                  newdata = newdat, 
                                  type = "response")
  
  # Create a data frame to save the plot data
  plotdat <- data.frame(
    predictor = predictor_seq,
    fit = predicted_values
  )
  
  return(list(plotdat = plotdat))
}

```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  print(current_peak)
  
  # Clean the model name to avoid duplication
  clean_model_name <- sub("_mature$", "", model_name)
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", clean_model_name, "| Significant Developmental Change:", toString(dev_change)))

  # Generate data for the current fitting curve
  raw_result <- generate_plotdat_for_predictor(
    model = current_model,
    predictor = 'mature',
    seq_range = c(-30.90410959, 16.93150685),
    length_out = 100
  )
  current_plot_data <- raw_result$plotdat

  # Add the current plot data to the combined data frame
  current_plot_data$model_name <- clean_model_name
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
}
```

```{r}
# Save the data frame to a CSV file
write.csv(combined_plot_data, "predicted_FA_vs_mature.csv", row.names = FALSE)
```

  
 