#setup working dir
load libraries
define some functions
```{r}
# Set the working directory to the specified path
setwd("C:/Users/cclab/Documents/GitHub/Dev2019/GAM")

# Load necessary libraries/packages
library(dplyr)      # Data manipulation 
library(ggplot2)    # Data visualization
library(gratia)     # Tools for GAM models
library(gridExtra)  # Arranging ggplot2 plots on a grid
library(lubridate)  # Work with date-times
library(mgcv)       # GAM and GAMM functions
library(purrr)      # Functional programming tools
library(stringr)    # String manipulation
library(tidyr)      # Data tidying
library(xtable)     # Export tables to various formats
library(LNCDR)
library(cowplot)  # For arranging plots and legends
```


```{r}
# Define a function to plot raw data, fitted values, and pointwise 95% confidence intervals from a GAMM
plot_gamm <- function(model,predictor = 'age', x_axis_label = '', y_axis_label = '', sig = TRUE, color_map = NULL) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]]
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  plotdat <- data.frame(cbind(dat_clean[[predictor]], pred$fit, pred$se))
  plotdat <- plotdat %>% 
    mutate(outcome = 1) 
  names(plotdat) <- c(predictor, 'fit', 'se', outcome)
  
  # If a color map is provided, use it. Otherwise, use the default color.
  if (!is.null(color_map)) {
    individual_colors <- dat$ID %>% as.character() %>% factor() %>% levels() %>% setNames(., .) %>% color_map[.]
  } else {
    individual_colors <- "blue"  # or any other default color you'd like
  }
  if (sig == TRUE){
    plotcolor_fit <- '#476FD1'
  } else {
    plotcolor_fit <- 'grey50'
  }
  gammplot <- ggplot(dat, aes_string(x = predictor, y = outcome, group = "ID", color = "ID")) + 
    geom_line(alpha = .3) + 
    geom_point(alpha = .3, shape = 16) +
    (if (!is.null(color_map)) scale_color_manual(values = color_map) else scale_color_identity()) +
    geom_ribbon(data = plotdat, aes_string(x = predictor, ymin = "fit - (1.96 * se)", ymax = "fit + (1.96 * se)"), alpha = .6, fill = plotcolor_fit, inherit.aes = FALSE) + 
    geom_line(data = plotdat, aes_string(x = predictor, y = "fit"), color = plotcolor_fit, inherit.aes = FALSE) + 
    
    labs(x = x_axis_label, 
         y = y_axis_label) +
    theme_bw() +
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = 'black')) +
    theme(axis.title = element_text(size = 11),
          axis.text = element_text(size = 10))
  return(gammplot)
}

# Define a function for post-hoc analysis to identify periods of developmental change
calc_dev_change <- function(model) {
  # Calculate derivatives of the model
  deriv <- gratia::derivatives(model)
  deriv <- deriv %>%
    mutate(sig = !(0 > lower & 0 < upper)) 
  # Identify range of significant change
  ranges <- list(c(min(deriv$data[deriv$sig == TRUE]), 
                   max(deriv$data[deriv$sig == TRUE])))
  return(ranges[[1]])
}

get_peak_and_velocity <- function(model, predictor = 'age') {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]]
  # Clean the data
  dat_clean <- dat %>% drop_na(all_of(outcome))
  
  # Create new data for prediction
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  
  # Predict the values
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Create a dataframe with predictions
  pred_dat <- data.frame(predictor = dat_clean[[predictor]], fit = pred$fit)
  
  # Find the peak value's predictor (e.g., age at which outcome is maximized)
  peak_x <- pred_dat$predictor[which.max(pred_dat$fit)]
  peak_y <- max(pred_dat$fit)
  
  # Determine the Peak Rate of Change (Velocity)
  derivi <- gratia::derivatives(model$gam)
  peak_velocity_x <- derivi$data[which.max(abs(derivi$derivative))]
  closest_idx <- which.min(abs(pred_dat$predictor - peak_velocity_x))
  peak_velocity_y <- pred_dat$fit[closest_idx]
  
  return(list(peak_value_x = peak_x, peak_velocity_x = peak_velocity_x, peak_value_y = peak_y, peak_velocity_y = peak_velocity_y))
}

my_color <- c("OLI" = "#E73133", "PIC" = "#4B8BBF", "QUA" = "#5FB75C", "ROS" = "#FF8C1A",
              "SON" = "#DDCF6E", "TRI" = "#AF673E", "UNI" = "#F88EC5", "VIK" = "#A3A3A3")
```

# read data
```{r}
# Read the dataset from a CSV file
dat <- read.csv('vol_charm2_contraonly.csv',
                stringsAsFactors = FALSE)
# # Read the dataset from a CSV file
# dat <- read.csv('vol_Aseg_GM_contraonly.csv', 
#                 stringsAsFactors = FALSE) 
```

# clean data
```{r}
# Read the dataset from a CSV file
header_list <- as.list(names(dat))
names_to_omit <- c('ID','mature','age','session','hemi','sex')
header_list <- header_list[-match(names_to_omit, header_list)]

listregions_all =  header_list
print(listregions_all)
```

```{r}
listregions1 <- c('White_Matter', 'SC', 'Cortex', 'Hippocampus', 'Amygdala')
listregions1b <- c('Brain_Stem', 'Cerebellum_White_Matter', 'Cerebellum_Cortex')
listregions2 <- c("Frontal", "Parietal", "Temporal", "Occipital")
listregions2b <- c("telencephalon", "diencephalon", "mesencephalon", "metencephalon", "myelencephalon")
listregions3 <- c('somatosensory_cortex',
                  'superior_parietal_lobule',
                  'inferior_parietal_lobule',
                  'posterior_medial_cortex')
listregions4 <- c('anterior_cingulate_gyrus',
                  'orbital_frontal_cortex',
                  'lateral_prefrontal_cortex',
                  'motor_cortex')
listregions5 <- c('medial_temporal_lobe',
                  'temporal_pole',
                  'inferior_temporal_cortex',
                  'superior_temporal_region',
                  'core_and_belt_areas_of_auditory_cortex',
                  'floor_of_the_lateral_sulcus',
                  'middle_temporal_area')
listregions6 <- c('extrastriate_visual_areas_2_4',
                  'primary_visual_cortex')

listregions7 <- c('lateral_and_ventral_pallium', 'medial_pallium','amygdala','basal_ganglia','diagonal_subpallium','preoptic_complex','hypothalamus')
listregions8 <- c('prethalamus','thalamus','epithalamus','pretectum')
listregions9 <- c('midbrain','pons','cerebellum','medulla')

listregions_all =  list(listregions1, listregions1b, listregions2, listregions2b, listregions3, listregions4, listregions5, listregions6, listregions7, listregions8, listregions9)
listregions_name =  c('seg','segSC', 'lobes', 'lobesSC', 'parietal', 'frontal', 'temporal', 'occipital', 'limbic', 'diencephalon', 'brainstem_and_cerebellum')
```
# modeling on age
```{r}
list_of_regressor = c('age')
list_of_regressor_string = c('age')

# Initialize a list to store the models
models_age_list <- list()
peak_and_velocity_age_list <- list()
for(L in 1:length(list_of_regressor)){
  regressor = list_of_regressor[L]
  regressor_string = list_of_regressor_string[L]
  
  for(R in 1:length(listregions_all)){
    current_regions = listregions_all[[R]]
    region_name = listregions_name[R]
    
    for(region in current_regions){
      print(paste("Regressor:", regressor, "| Region:", region))
      
      # Define a formula for the GAMM to model the current 'region' as a smoothed function of the current 'regressor'
      model_formula <- as.formula(paste(region, "~ s(", regressor, ", k = 5, fx = FALSE, bs = 'cs')"))
      
      # Fit the GAMM with the formula, and a random effect of 'id' on the current 'regressor'
      gamm_vol_on_dev <- gamm(as.formula(model_formula), 
                              # family = 'quasibinomial',
                              random = list(ID=~1+age),
                              data = dat %>% drop_na(all_of(c(region, regressor))),
                              method = 'REML')
      peak_and_velocity <- get_peak_and_velocity(model = gamm_vol_on_dev, predictor = regressor)
      # Save the model to the list
      model_name <- paste(region, regressor, sep="_")
      models_age_list[[model_name]] <- gamm_vol_on_dev
      peak_and_velocity_age_list[[model_name]] <- peak_and_velocity
    }
  }
}
```
# modeling on mature
```{r}
list_of_regressor = c('mature')
list_of_regressor_string = c('mature')

# Initialize a list to store the models
models_mat_list <- list()
peak_and_velocity_mat_list <- list()

for(L in 1:length(list_of_regressor)){
  regressor = list_of_regressor[L]
  regressor_string = list_of_regressor_string[L]
  
  for(R in 1:length(listregions_all)){
    current_regions = listregions_all[[R]]
    # region_name = listregions_name[R]
    
    for(region in current_regions){
      print(paste("Regressor:", regressor, "| Region:", region))
      
      # Define a formula for the GAMM to model the current 'region' as a smoothed function of the current 'regressor'
      model_formula <- as.formula(paste(region, "~ s(", regressor, ", k = 10, fx = FALSE, bs = 'tp')"))
      
      # Fit the GAMM with the formula, and a random effect of 'id' on the current 'regressor'
      gamm_vol_on_dev <- gamm(as.formula(model_formula), 
                              # family = 'quasibinomial',
                              random = list(ID=~1+mature),
                              data = dat %>% drop_na(all_of(c(region, regressor))),
                              method = 'REML')
      peak_and_velocity <- get_peak_and_velocity(model = gamm_vol_on_dev, predictor = regressor)
      # Save the model to the list
      model_name <- paste(region, regressor, sep="_")
      models_mat_list[[model_name]] <- gamm_vol_on_dev
      peak_and_velocity_mat_list[[model_name]] <- peak_and_velocity
    }
  }
}
```
#plot on age
```{r}
# Loop through the model names in models_list
for(model_name in names(models_age_list)) {
  
  # Extract the current model
  current_model <- models_age_list[[model_name]]
  current_peak <- peak_and_velocity_age_list[[model_name]]
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 57.9
  } else {
    sig <- TRUE
  }
  
  # Plot this model
  current_plot <- plot_gamm(
    predictor = 'age',
    model = current_model, 
    y_axis_lab = 'Outcome Value',
    sig = sig, color_map = my_color)
  # Annotate the plot with a bar indicating significant developmental change
  # Extract y-axis range from current_plot
  y_range <- layer_scales(current_plot)$y$range$range
  
  # Set ymin and ymax based on y_range
  ymin_value <- y_range[1] - 0.01 * (y_range[2] - y_range[1])
  ymax_value <- y_range[1] 
  
  current_plot <- current_plot + labs(title = model_name) +
    annotate(geom = "rect", 
             xmin = dev_change[1], 
             xmax = dev_change[2], 
             ymin = ymin_value, 
             ymax = ymax_value, 
             fill = '#476FD1') +
    geom_point(aes(x = current_peak$peak_value_x, y = current_peak$peak_value_y), shape = 24, size = 3, color = "red") +
    geom_point(aes(x = current_peak$peak_velocity_x, y = current_peak$peak_velocity_y, type = "response"), shape = 1, size = 3, color = "blue")+
    geom_vline(xintercept = 57.9, linetype="dashed", color = "brown")
  print(current_plot)
  
  # Define file names based on the model name
  png_file_name <- paste0(model_name, '.png')
  pdf_file_name <- paste0(model_name, '.pdf')
  
  # Save the plot in PNG format
  #ggsave(png_file_name, plot = current_plot, device = 'png', width = 8, height = 4, dpi = 300)
  
  # Save the plot in PDF format
  #ggsave(pdf_file_name, plot = current_plot, device = 'pdf', width = 8, height = 4)
}
```

# plot on mature
```{r}
# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }
  # Plot this model
  current_plot <- plot_gamm(
    predictor = 'mature',
    model = current_model, 
    y_axis_lab = 'Outcome Value',
    sig = sig, color_map = my_color)
  # Annotate the plot with a bar indicating significant developmental change
  # Extract y-axis range from current_plot
  y_range <- layer_scales(current_plot)$y$range$range
  # Set ymin and ymax based on y_range
  ymin_value <- y_range[1] - 0.01 * (y_range[2] - y_range[1])
  ymax_value <- y_range[1] 
  
  current_plot <- current_plot + labs(title = model_name) +
    annotate(geom = "rect", 
             xmin = dev_change[1], 
             xmax = dev_change[2], 
             ymin = ymin_value, 
             ymax = ymax_value, 
             fill = '#476FD1') +
    geom_point(aes(x = current_peak$peak_value_x, y = current_peak$peak_value_y), shape = 24, size = 3, color = "red") +
    geom_point(aes(x = current_peak$peak_velocity_x, y = current_peak$peak_velocity_y, type = "response"), shape = 1, size = 3, color = "blue") +
    geom_vline(xintercept = 0, linetype="dashed", color = "brown") +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 5, hjust = 1),
          axis.text.x = element_text(size = 5, angle = 0, hjust = 1),
          plot.title = element_text(size = 7, face = "bold", hjust = 0.5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(colour = "black"))+
    scale_x_continuous(labels = function(x) x)+
    labs(x = "Maturation age", y = "Volume")
  print(current_plot)
  # Define file names based on the model name
  png_file_name <- paste0(model_name, '.png')
  pdf_file_name <- paste0(model_name, '.pdf')
  
  # # Save the plot in PNG format
  ggsave(png_file_name, plot = current_plot, device = 'png', width = 3, height = 3, dpi = 300)
  # 
  # # Save the plot in PDF format
  ggsave(pdf_file_name, plot = current_plot, device = 'pdf', width = 3, height = 3)
}
```

# find dev change for 3d rendering
```{r}
# Initialize a dataframe to store the summary results
summary_table <- data.frame(
  ModelName = character(),
  DevChangeStart = numeric(),
  DevChangeEnd = numeric(),
  DevChangePercentage = numeric(),
  PeakValueX = numeric(),
  PeakValueY = numeric(),
  PeakVelocityX = numeric(),
  PeakVelocityY = numeric(),
  stringsAsFactors = FALSE
)


# Loop through each model to extract the necessary information
for (model_name in names(models_mat_list)) {
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  
  # Extract the region name from the model name
  model_name_parts <- strsplit(model_name, "_")[[1]]
  region_name <- paste(model_name_parts[1:(length(model_name_parts)-1)], collapse = "_")
  
  dev_change <- calc_dev_change(current_model)
  peak_and_velocity <- peak_and_velocity_mat_list[[model_name]]
  
  # Initialize a row to append to the summary table
  result_row <- data.frame(
    ModelName = model_name,
    DevChangeStart = NA,
    DevChangeEnd = NA,
    DevChangePercentage = NA,
    PeakValueX = NA,
    PeakValueY = NA,
    PeakVelocityX = NA,
    PeakVelocityY = NA,
    stringsAsFactors = FALSE
  )
  
  # Check if either development change point is infinite
  if (is.infinite(dev_change[1]) || is.infinite(dev_change[2])) {
    # Skip further processing and append the row with NAs
    summary_table <- rbind(summary_table, result_row)
  } else {
    # Calculate the total change percentage using min and max x
    min_x <- min(dat[[regressor]], na.rm = TRUE)
    max_x <- max(dat[[regressor]], na.rm = TRUE)
    
    # Proceed with generating predictions only if dev_change values are finite
    new_data <- data.frame(mature = c(min_x, dev_change[2]))
    names(new_data) <- regressor  # Ensure the column name uses the dynamic regressor name
    
    predictions <- predict(current_model$gam, new_data, type = "response")
    
    # Calculate the developmental change percentage if predictions are valid
    if (length(predictions) == 2) {
      result_row$DevChangePercentage <- (predictions[2] - predictions[1]) / predictions[1]
    }

    derivi <- gratia::derivatives(current_model$gam)
  peak_velocity_x <- derivi$data[which.max(abs(derivi$derivative))]
    peak_velocity_y <- max(abs(derivi$derivative))

    
    result_row$DevChangeStart <- dev_change[1]
    result_row$DevChangeEnd <- dev_change[2]
    result_row$PeakValueX <- peak_and_velocity$peak_value_x
    result_row$PeakValueY <- peak_and_velocity$peak_value_y
    result_row$PeakVelocityX <- peak_velocity_x
    result_row$PeakVelocityY <- peak_velocity_y
    
    # Append the updated row to the summary table
    summary_table <- rbind(summary_table, result_row)
  }
}

# Display the summary table
print(summary_table)
```

```{r}
# Save the summary table as a CSV file
write.csv(summary_table, "vol_Aseg_summary_table.csv", row.names = FALSE)
```

```{r}
# Loop through each model to extract the necessary information
for (model_name in names(models_mat_list)) {
  model <- models_mat_list[[model_name]]
  dev_change <- calc_dev_change(model$gam)
  peak_and_velocity <- peak_and_velocity_mat_list[[model_name]]
  
  # Check if either development change point is infinite
  if (is.infinite(dev_change[1]) || is.infinite(dev_change[2])) {
    # Set all results for this model to NA
    summary_table <- rbind(summary_table, data.frame(
      ModelName = model_name,
      DevChangeStart = NA,
      DevChangeEnd = NA,
      DevChangePercentage = NA,
      TotalChangePercentage = NA,
      PeakValueX = NA,
      PeakValueY = NA,
      PeakVelocityX = NA,
      PeakVelocityY = NA
    ))
  } else {
    # Calculate the total change percentage using min and max x
    min_x <- min(dat[[regressor]], na.rm = TRUE)
    max_x <- max(dat[[regressor]], na.rm = TRUE)
    
    extreme_data <- data.frame(mature = c(min_x, max_x))
    names(extreme_data) <- regressor
    
    extreme_predictions <- predict(model$gam, extreme_data, type = "response")
    total_change_percentage <- if (length(extreme_predictions) == 2) {
      (extreme_predictions[2] - extreme_predictions[1]) / extreme_predictions[1] * 100
    } else {
      NA
    }
    
    # Prepare data for predicting at dev change points
    new_data <- data.frame(mature = c(dev_change[1], dev_change[2]))
    names(new_data) <- regressor
    
    predictions <- predict(model$gam, new_data, type = "response")
    dev_change_percentage <- if (length(predictions) == 2) {
      predictions[2] / predictions[1]
    } else {
      NA
    }
    
    # Append the results to the summary table
    summary_table <- rbind(summary_table, data.frame(
      ModelName = model_name,
      DevChangeStart = dev_change[1],
      DevChangeEnd = dev_change[2],
      DevChangePercentage = dev_change_percentage,
      TotalChangePercentage = total_change_percentage,
      PeakValueX = peak_and_velocity$peak_value_x,
      PeakValueY = peak_and_velocity$peak_value_y,
      PeakVelocityX = peak_and_velocity$peak_velocity_x,
      PeakVelocityY = peak_and_velocity$peak_velocity_y
    ))
  }
}
print(summary_table)
```


# heatmap of changing timing
```{r}
# Initialize an empty data frame to store dev_change information
dev_change_df <- data.frame(region = character(),
                            mature_value = numeric(),
                            region_value = numeric(),
                            percent_change = numeric(),
                            stringsAsFactors = FALSE)

# Initialize an empty data frame to store regions with infinite dev_change
inf_dev_change_df <- data.frame(region = character(),
                                mature_value = numeric(),
                                region_value = numeric(),
                                percent_change = numeric(),
                                stringsAsFactors = FALSE)

for (model_name in names(models_mat_list)) {
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  
  # Extract the region name from the model name
  model_name_parts <- strsplit(model_name, "_")[[1]]
  region_name <- paste(model_name_parts[1:(length(model_name_parts)-1)], collapse = "_")
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  
  if (all(is.infinite(dev_change))) {
    # Add the region with infinite dev_change to inf_dev_change_df
    inf_dev_change_df <- rbind(inf_dev_change_df, data.frame(region = region_name,
                                                             mature_value = NA,
                                                             region_value = 0,
                                                             percent_change = 0,
                                                             stringsAsFactors = FALSE))
  } else {
    # Create a sequence of points within the significant change period using 1/10 of the mature value as the step length
    mature_values <- seq(from = dev_change[1], to = dev_change[2], by = 1)
    
    # Predict the region values at each point
    region_values <- predict(current_model$gam, newdata = data.frame(mature = mature_values))
    
    # Calculate the percentage change in the region values
    percent_changes <- c(NA, diff(region_values) / region_values[-length(region_values)] * 100)
    
    # Add the dev_change information to the data frame
    dev_change_df <- rbind(dev_change_df, data.frame(region = rep(region_name, length(mature_values)),
                                                     mature_value = mature_values,
                                                     region_value = region_values,
                                                     percent_change = percent_changes,
                                                     stringsAsFactors = FALSE))
  }
}

# Combine dev_change_df and inf_dev_change_df
combined_df <- rbind(dev_change_df, inf_dev_change_df)
```


```{r}
# Calculate the start and end positions for each rectangle
combined_df <- combined_df %>%
  group_by(region) %>%
  mutate(start = lag(mature_value, default = first(mature_value)),
         end = lead(mature_value, default = last(mature_value))) %>%
  ungroup()

# Calculate the length of dev_change for each region
region_dev_change_length <- combined_df %>%
  group_by(region) %>%
  summarize(dev_change_length = max(mature_value))

# Sort the regions based on dev_change_length
sorted_regions <- region_dev_change_length$region[order(region_dev_change_length$dev_change_length)]

# Create the plot using geom_rect
current_plot <- ggplot(combined_df, aes(xmin = start,
                                        xmax = end,
                                        ymin = as.numeric(factor(region, levels = sorted_regions)) - 0.4,
                                        ymax = as.numeric(factor(region, levels = sorted_regions)) + 0.4,
                                        fill = percent_change)) +
  geom_rect() +
  scale_fill_gradient2(low = "darkblue", mid = "white", high = "red", midpoint = 0,
                       name = "% change per month",
                       limits = range(c(0, 1.5), na.rm = TRUE)) +
  labs(x = "Maturation age", y = "region", title = "Volume") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 10, hjust = 1),
        axis.text.x = element_text(size = 10, angle = 0, hjust = 1),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(breaks = seq_along(sorted_regions), labels = sorted_regions)

print(current_plot)
```


save plot
```{r}
# Define file names based on the model name
png_file_name1 <- paste0('vol_Charm1_timing.png')
pdf_file_name1 <- paste0('vol_Charm1_timing.pdf')

# Save the plot in PNG format
ggsave(png_file_name1, plot = current_plot, device = 'png', width = 6, height = 6, dpi = 300)

# Save the plot in PDF format
ggsave(pdf_file_name1, plot = current_plot, device = 'pdf', width = 6, height = 6)
```

```{r}
# Function to create the plot for a specific region list
create_plot <- function(region_list, plot_name) {
  # Filter the combined_df based on the regions in the current list
  filtered_df <- combined_df[combined_df$region %in% region_list, ]
  
  # Calculate the length of dev_change for each region in the current list
  region_dev_change_length <- filtered_df %>%
    group_by(region) %>%
    summarize(dev_change_length = max(mature_value))
  
  # Sort the regions based on dev_change_length
  sorted_regions <- region_dev_change_length$region[order(region_dev_change_length$dev_change_length)]
  
  # Set a fixed y-axis range for all plots
  y_range <- c(0.5, 7.5)
  
  # Create the plot using geom_rect
  plot <- ggplot(filtered_df, aes(xmin = start,
                                  xmax = end,
                                  ymin = as.numeric(factor(region, levels = sorted_regions)) - 0.4,
                                  ymax = as.numeric(factor(region, levels = sorted_regions)) + 0.4,
                                  fill = percent_change)) +
    geom_rect() +
    scale_fill_gradient2(low = "darkblue", mid = "white", high = "red",
                         midpoint = 0,
                         limits = c(0, 1.1),
                         name = "% Change per month") +
    labs(x = "Maturation age", y = "Region", title = plot_name) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 10, angle = 30, hjust = 1),
          axis.text.x = element_text(size = 10,hjust = 1),
          plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(colour = "black")) +
    scale_y_continuous(breaks = seq_along(sorted_regions), labels = sorted_regions)+
    coord_cartesian(ylim = y_range)
  
  return(plot)
}

# Initialize an empty list to store the plots
plot_list <- list()

# Calculate the start and end positions for each rectangle
combined_df <- combined_df %>%
  group_by(region) %>%
  mutate(start = lag(mature_value, default = first(mature_value)),
         end = lead(mature_value, default = last(mature_value))) %>%
  ungroup()

# Iterate over each region list and create a plot for each one
for (i in seq_along(listregions_all)) {
  region_list <- listregions_all[[i]]
  plot_name <- listregions_name[i]
  
  plot_list[[plot_name]] <- create_plot(region_list, plot_name)
}

# Print or save the plots as needed
for (plot_name in names(plot_list)) {
  print(plot_list[[plot_name]])
  ggsave(paste0(plot_name, ".png"), plot_list[[plot_name]], width = 6, height = 6)
  ggsave(paste0(plot_name, ".pdf"), plot_list[[plot_name]], width = 6, height = 6)
}
```


# stats
```{r}
# summary of significance of smooth terms for age for final models
# Extract model names from the list
model_names <- names(models_age_list)

# Extract significance information for each model
sumtab <- sapply(model_names, function (x) {
  model_gam <- models_age_list[[x]]$gam
  summary(model_gam)$s.table
})

AIC_r2 <- sapply(model_names, function (x) {
  model <- models_age_list[[x]]
  # Extract AIC
  aic_val <- summary(model$lme)$AIC
  # Extract R^2 (Percent deviance explained)
  r2_val <- summary(model$gam)$r.sq
  
  c(AIC = aic_val, R2 = r2_val)
  
})
AIC_r2_df <- as.data.frame(t(AIC_r2))

# Format the results
rownames(sumtab) <- c('edf', 'Ref.df', 'F', 'p-value')
sumtab <- as.data.frame(t(sumtab)) %>%
  tibble::rownames_to_column(., 'model') %>%
  select(-c('Ref.df'))
sumtab <- cbind(sumtab, p.adjust(sumtab$`p-value`, method = 'fdr'))
names(sumtab)[ncol(sumtab)] <- 'q-value'
sumtab <- sumtab %>% 
  mutate(survive_multcomp = ifelse(`q-value` < 0.05, 1, 0))
AIC_r2_df$model <- rownames(AIC_r2_df)
# Combine results
combined_df <- merge(sumtab, AIC_r2_df, by = "model")

# Save the results as a CSV
write.csv(combined_df, file = "vol_age_results.csv", row.names = FALSE)

```

```{r}
# summary of significance of smooth terms for mature for final models
# Extract model names from the list
model_names <- names(models_mat_list)

# Extract significance information for each model
sumtab <- sapply(model_names, function (x) {
  model_gam <- models_mat_list[[x]]$gam
  summary(model_gam)$s.table
})

AIC_r2 <- sapply(model_names, function (x) {
  model <- models_mat_list[[x]]
  # Extract AIC
  aic_val <- summary(model$lme)$AIC
  # Extract R^2 (Percent deviance explained)
  r2_val <- summary(model$gam)$r.sq
  
  c(AIC = aic_val, R2 = r2_val)
  
})
AIC_r2_df <- as.data.frame(t(AIC_r2))

# Format the results
rownames(sumtab) <- c('edf', 'Ref.df', 'F', 'p-value')
sumtab <- as.data.frame(t(sumtab)) %>%
  tibble::rownames_to_column(., 'model') %>%
  select(-c('Ref.df'))
sumtab <- cbind(sumtab, p.adjust(sumtab$`p-value`, method = 'fdr'))
names(sumtab)[ncol(sumtab)] <- 'q-value'
sumtab <- sumtab %>% 
  mutate(survive_multcomp = ifelse(`q-value` < 0.05, 1, 0))
AIC_r2_df$model <- rownames(AIC_r2_df)

# Combine results
combined_df <- merge(sumtab, AIC_r2_df, by = "model")

# # Save the results as a CSV
# write.csv(combined_df, file = "vol_mat_results.csv", row.names = FALSE)
```

# plot overlay curves
```{r}
plot_gamm_fitting_curves_normalized <- function(model, predictor = 'age', sig = TRUE) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]] %>% str_trim()
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  plotdat <- data.frame(cbind(dat_clean[[predictor]], pred$fit, pred$se))
  plotdat <- plotdat %>% 
    mutate(model_name = outcome) 
  names(plotdat) <- c(predictor, 'fit', 'se', 'model_name')

  # Normalize the fitted values and scale as percentage of the max value
  max_fit <- max(plotdat$fit, na.rm = TRUE)
  plotdat <- plotdat %>%
    mutate(fit = (fit / max_fit) * 100,
           se = (se / max_fit) * 100,
           fit = fit - 100) # Mark the max value as 0
  
  return(list(plotdat = plotdat, max_fit = max_fit))
}
```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  print(current_peak)
  
  # Clean the model name to avoid duplication
  clean_model_name <- sub("_mature$", "", model_name)
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", clean_model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }

  # Generate data for the current fitting curve
  normalized_result <- plot_gamm_fitting_curves_normalized(
    model = current_model,
    predictor = 'mature',
    sig = sig
  )
  current_plot_data <- normalized_result$plotdat
  max_fit <- normalized_result$max_fit

  # Add the current plot data to the combined data frame
  current_plot_data$model_name <- clean_model_name
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
  
  # Only add max value and max velocity points if the curve is significant somewhere
  if (sig) {
    max_value_normalized <- (current_peak$peak_value_y / max_fit) * 100 - 100
    max_velocity_normalized <- (current_peak$peak_velocity_y / max_fit) * 100 - 100
    
    max_points <- data.frame(
      x = c(current_peak$peak_value_x, current_peak$peak_velocity_x),
      y = c(max_value_normalized, max_velocity_normalized),
      model_name = clean_model_name,
      point_type = c("max_value", "max_velocity")
    )
    
    max_points_data <- rbind(max_points_data, max_points)
  }
}

# Plot all fitting curves together
combined_plot <- ggplot(combined_plot_data, aes(x = mature, y = fit, color = model_name)) + 
  geom_ribbon(aes(ymin = fit - (1.96 * se), ymax = fit + (1.96 * se)), alpha = 0, linetype = "dashed", size = 0.1, show.legend = FALSE) + 
  geom_line(size = 1) +
  geom_point(data = max_points_data %>% filter(point_type == "max_value"),
             aes(x = x, y = y, color = model_name), shape = 24, size = 4, show.legend = FALSE) +
  geom_point(data = max_points_data %>% filter(point_type == "max_velocity"),
             aes(x = x, y = y, color = model_name), shape = 1, size = 4, show.legend = FALSE) +
  labs(x = 'Mid-adolescence age (mon.)', y = 'Normalized volume (Percentage of Max)') +
  coord_fixed(ratio = 4/1) +  # Lock the aspect ratio to 3:4
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = 'black')) +
  theme(axis.title = element_text(size = 11),
        axis.text = element_text(size = 10),
    legend.text = element_text(size = 8), # Reduce legend text size
    legend.key.size = unit(0.5, "lines")  # Reduce legend key size
  )

# Save the combined plot
ggsave('vol_lobe_combined_plot.png', plot = combined_plot, device = 'png', width = 6, height = 6, dpi = 300)
ggsave('vol_lobe_combined_plot.pdf', plot = combined_plot, device = 'pdf', width = 6, height = 6)

# Print the combined plot
print(combined_plot)
```
# plot overlay curves raw
```{r}
plot_gamm_fitting_curves_raw <- function(model, predictor = 'age', sig = TRUE) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]] %>% str_trim()
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Calculate raw fitted values, standard errors, and confidence intervals
  plotdat <- data.frame(
    predictor = dat_clean[[predictor]],
    fit = pred$fit,
    se = pred$se.fit,
    lower = pred$fit - 1.96 * pred$se.fit,
    upper = pred$fit + 1.96 * pred$se.fit
  )
  plotdat <- plotdat %>% mutate(model_name = outcome)
  
  return(list(plotdat = plotdat))
}

```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  print(current_peak)
  
  # Clean the model name to avoid duplication
  clean_model_name <- sub("_mature$", "", model_name)
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", clean_model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }

  # Generate data for the current fitting curve
  raw_result <- plot_gamm_fitting_curves_raw(
    model = current_model,
    predictor = 'mature',
    sig = sig
  )
  current_plot_data <- raw_result$plotdat

  # Add the current plot data to the combined data frame
  current_plot_data$model_name <- clean_model_name
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
  
  # Only add max value and max velocity points if the curve is significant
  if (sig) {
    max_points <- data.frame(
      x = c(current_peak$peak_value_x, current_peak$peak_velocity_x),
      y = c(current_peak$peak_value_y, current_peak$peak_velocity_y),
      model_name = clean_model_name,
      point_type = c("max_value", "max_velocity")
    )
    
    max_points_data <- rbind(max_points_data, max_points)
  }
}

# Ensure the combined data has the correct column names
names(combined_plot_data)[1] <- "mature"

# Create the combined plot
combined_plot <- ggplot(combined_plot_data, aes(x = mature, y = fit, color = model_name)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0, linetype = "dashed", size = 0.5, show.legend = FALSE) + 
  geom_line(size = 1) +
  geom_point(data = max_points_data %>% filter(point_type == "max_value"),
             aes(x = x, y = y, color = model_name), shape = 24, size = 3, show.legend = FALSE) +
  geom_point(data = max_points_data %>% filter(point_type == "max_velocity"),
             aes(x = x, y = y, color = model_name), shape = 1, size = 3, show.legend = FALSE) +
  labs(x = 'Mid-adolescence age (mon.)', y = 'Volume') +
  theme_bw() +
  theme(
    panel.border = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.line = element_line(colour = 'black'),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    legend.position = c(0.85, 0.85), # Position legend inside the plot (x, y coordinates in [0, 1] range)
    legend.background = element_rect(fill = alpha('white', 0.5)), # Semi-transparent background for the legend
    legend.text = element_text(size = 8), # Reduce legend text size
    legend.key.size = unit(0.5, "lines")  # Reduce legend key size
  )

# Save the combined plot
ggsave('vol_seg_combined_plot_raw.png', plot = combined_plot, device = 'png', width = 6, height = 6, dpi = 300)
ggsave('vol_seg_combined_plot_raw.pdf', plot = combined_plot, device = 'pdf', width = 6, height = 6)

# Print the combined plot
print(combined_plot)

```
# plot overlay curves centered at 0
```{r}
plot_gamm_fitting_curves_centered <- function(model, predictor = 'age', center_at = 0, sig = TRUE) {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]] %>% str_trim()
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor
  
  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Calculate raw fitted values, standard errors, and confidence intervals
  plotdat <- data.frame(
    predictor = dat_clean[[predictor]],
    fit = pred$fit,
    se = pred$se.fit,
    lower = pred$fit - 1.96 * pred$se.fit,
    upper = pred$fit + 1.96 * pred$se.fit
  )
  plotdat <- plotdat %>% mutate(model_name = outcome)
  
  # Find the value closest to the center_at value
  nearest_index <- which.min(abs(plotdat$predictor - center_at))
  center_value <- plotdat$fit[nearest_index]
  
  # Center the fitted values at the nearest value
  plotdat <- plotdat %>%
    mutate(
      fit = fit - center_value,
      lower = lower - center_value,
      upper = upper - center_value
    )
  
  return(list(plotdat = plotdat, center_value = center_value))
}

```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  print(current_peak)
  
  # Clean the model name to avoid duplication
  clean_model_name <- sub("_mature$", "", model_name)
  
  # Identify significant periods of developmental change using the calc_dev_change function
  dev_change <- calc_dev_change(current_model)
  print(paste("Model:", clean_model_name, "| Significant Developmental Change:", toString(dev_change)))
  if (all(is.infinite(dev_change))) {
    sig <- FALSE
    dev_change <- 0
  } else {
    sig <- TRUE
  }

  # Generate data for the current fitting curve
  centered_result <- plot_gamm_fitting_curves_centered(
    model = current_model,
    predictor = 'mature',
    center_at = 0,
    sig = sig
  )
  current_plot_data <- centered_result$plotdat
  center_value <- centered_result$center_value

  # Add the current plot data to the combined data frame
  current_plot_data$model_name <- clean_model_name
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
  
  # Only add max value and max velocity points if the curve is significant
  if (sig) {
    max_points <- data.frame(
      x = c(current_peak$peak_value_x, current_peak$peak_velocity_x),
      y = c(current_peak$peak_value_y - center_value, current_peak$peak_velocity_y - center_value),
      model_name = clean_model_name,
      point_type = c("max_value", "max_velocity")
    )
    
    max_points_data <- rbind(max_points_data, max_points)
  }
}

# Ensure the combined data has the correct column names
names(combined_plot_data)[1] <- "mature"

# Create the combined plot
combined_plot <- ggplot(combined_plot_data, aes(x = mature, y = fit, color = model_name)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0, linetype = "dashed", size = 0.1, show.legend = FALSE) + 
  geom_line(size = 1) +
  geom_point(data = max_points_data %>% filter(point_type == "max_value"),
             aes(x = x, y = y, color = model_name), shape = 24, size = 3, show.legend = FALSE) +
  geom_point(data = max_points_data %>% filter(point_type == "max_velocity"),
             aes(x = x, y = y, color = model_name), shape = 1, size = 3, show.legend = FALSE) +
  labs(x = 'Mid-adolescence age (mon.)', y = 'Normalized Volume') +
  theme_bw() +
  theme(
    panel.border = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.line = element_line(colour = 'black'),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    legend.position = c(0.85, 0.85), # Position legend inside the plot (x, y coordinates in [0, 1] range)
    legend.background = element_rect(fill = alpha('white', 0.5)), # Semi-transparent background for the legend
    legend.text = element_text(size = 8), # Reduce legend text size
    legend.key.size = unit(0.5, "lines")  # Reduce legend key size
  )
# 
# Save the combined plot
ggsave('vol_seg_combined_plot_centered.png', plot = combined_plot, device = 'png', width = 6, height = 6, dpi = 300)
ggsave('vol_seg_combined_plot_centered.pdf', plot = combined_plot, device = 'pdf', width = 6, height = 6)

# Print the combined plot
print(combined_plot)

```
# plot overlay curves raw with sig
```{r}
plot_gamm_fitting_curves_with_sig_epochs <- function(model, predictor = 'age') {
  outcome <- str_split(as.character(model$gam$formula), '~')[[2]] %>% str_trim()
  dat_clean <- dat %>% drop_na(all_of(outcome))
  newdat <- data.frame(dat_clean[[predictor]])
  names(newdat) <- predictor

  pred <- predict.gam(model$gam, 
                      newdata = newdat,
                      type = 'response', 
                      se.fit = TRUE)
  
  # Calculate raw fitted values, standard errors, and confidence intervals
  plotdat <- data.frame(
    predictor = dat_clean[[predictor]],
    fit = pred$fit,
    se = pred$se.fit,
    lower = pred$fit - 1.96 * pred$se.fit,
    upper = pred$fit + 1.96 * pred$se.fit
  )
  plotdat <- plotdat %>% mutate(model_name = outcome)

  # Identify significant epochs
  deriv <- gratia::derivatives(model$gam)
  deriv <- deriv %>%
    mutate(sig = !(0 > lower & 0 < upper))
  
  plotdat <- plotdat %>%
    mutate(sig = FALSE)
  
  if (any(deriv$sig)) {
    sig_intervals <- deriv %>%
      filter(sig) %>%
      summarise(start = min(data), end = max(data))
    
    plotdat <- plotdat %>%
      mutate(sig = ifelse(predictor >= sig_intervals$start & predictor <= sig_intervals$end, TRUE, FALSE))
  }

  # Ensure all NA values in the sig column are set to FALSE
  plotdat$sig[is.na(plotdat$sig)] <- FALSE

  return(list(plotdat = plotdat))
}

```

```{r}
# Initialize an empty data frame to store all fitting curves
combined_plot_data <- data.frame()
max_points_data <- data.frame()

# Loop through the model names in models_list
for(model_name in names(models_mat_list)) {
  
  # Extract the current model
  current_model <- models_mat_list[[model_name]]
  current_peak <- peak_and_velocity_mat_list[[model_name]]
  print(model_name)
  
  # Generate data for the current fitting curve
  plot_result <- plot_gamm_fitting_curves_with_sig_epochs(
    model = current_model,
    predictor = 'mature'
  )
  current_plot_data <- plot_result$plotdat
  current_plot_data$model_name <- model_name
  
  # Add the current plot data to the combined data frame
  combined_plot_data <- rbind(combined_plot_data, current_plot_data)
  
  # Only add max value and max velocity points if the curve is significant
  if (any(current_plot_data$sig)) {
    max_points <- data.frame(
      x = c(current_peak$peak_value_x, current_peak$peak_velocity_x),
      y = c(current_peak$peak_value_y, current_peak$peak_velocity_y),
      model_name = model_name,
      point_type = c("max_value", "max_velocity")
    )
    
    max_points_data <- rbind(max_points_data, max_points)
  }
}

# Ensure the combined data has the correct column names
names(combined_plot_data)[1] <- "mature"

# Function to create the plot
create_plot <- function(data) {
  ggplot(data) + 
    geom_ribbon(aes(x = mature, ymin = lower, ymax = upper, fill = model_name), alpha = 0.05) + 
    geom_line(data = data %>% filter(sig == TRUE), aes(x = mature, y = fit, color = model_name), size = 1) +
    geom_line(data = data %>% filter(sig == FALSE), aes(x = mature, y = fit, color = model_name), size = 0.5, linetype = "dashed") +
    geom_point(data = max_points_data %>% filter(point_type == "max_value"),
               aes(x = x, y = y, color = model_name), shape = 24, size = 4, show.legend = FALSE) +
    geom_point(data = max_points_data %>% filter(point_type == "max_velocity"),
               aes(x = x, y = y, color = model_name), shape = 1, size = 4, show.legend = FALSE) +
    labs(x = 'Mid-adolescence age (mon.)', y = 'Volume') +
    theme_bw() +
    theme(
      panel.border = element_blank(), 
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(), 
      axis.line = element_line(colour = 'black'),
      axis.title = element_text(size = 11),
      axis.text = element_text(size = 10),
      legend.position = "right", # Position legend inside the plot (x, y coordinates in [0, 1] range)
      legend.background = element_rect(fill = alpha('white', 0.5)), # Semi-transparent background for the legend
      legend.text = element_text(size = 8), # Reduce legend text size
      legend.key.size = unit(0.5, "lines")
    )
}

# Create and print the combined plot
combined_plot <- create_plot(combined_plot_data)

# Save the combined plot
ggsave('vol_Charm2_combined_plot_sig_epochs.png', plot = combined_plot, device = 'png', width = 12, height = 6, dpi = 300)
ggsave('vol_Charm2_combined_plot_sig_epochs.pdf', plot = combined_plot, device = 'pdf', width = 12, height = 6)

# Print the combined plot
print(combined_plot)

```
# percentage change overtime
```{r}
# Function to calculate percentage change over a specified range
calculate_percentage_change <- function(model, predictor, center, range_width = 10) {
  # Create new data for prediction
  newdat <- data.frame(predictor = seq(center - range_width / 2, center + range_width / 2, by = 1))
  names(newdat) <- predictor
  
  # Predict the values
  pred <- predict.gam(model$gam, newdata = newdat, type = 'response', se.fit = TRUE)
  
  # Calculate percentage change
  start_value <- pred$fit[1]
  end_value <- pred$fit[length(pred$fit)]
  percentage_change <- ((end_value - start_value) / start_value) * 100
  
  return(percentage_change)
}
```

```{r}
# Define the centers and the width for the range
centers <- c(-35, -25, -15, -5, 5, 15)
range_width <- 10

# Initialize a list to store the percentage change results
percentage_change_results <- list()

for(L in 1:length(list_of_regressor)){
  regressor = list_of_regressor[L]
  regressor_string = list_of_regressor_string[L]
  
  for(R in 1:length(listregions_all)){
    current_regions = listregions_all[[R]]
    
    for(region in current_regions){
      model_name <- paste(region, regressor, sep="_")
      model <- models_mat_list[[model_name]]
      
      # Calculate percentage changes for each center
      percentage_changes <- sapply(centers, function(center) {
        calculate_percentage_change(model, predictor = regressor, center = center, range_width = range_width)
      })
      
      # Store the results in the list
      percentage_change_results[[model_name]] <- percentage_changes
    }
  }
}

# Convert the list to a dataframe
percentage_change_df <- do.call(cbind, percentage_change_results)
rownames(percentage_change_df) <- centers
percentage_change_df <- as.data.frame(t(percentage_change_df))
names(percentage_change_df) <- paste(centers)

# Transpose the dataframe so each column is a region
percentage_change_df <- t(percentage_change_df)

# Export the dataframe to a CSV file
write.csv(percentage_change_df, file = "percentage_change_overtime_vol_charm2.csv", row.names = TRUE)
```

